Lab 1
antoniovay/Sem-4 pull request #5
Opened 2024-03-24 11:22 UTC by antoniovay

2024-03-26 15:16 UTC, tvz-041 requested changes

2024-03-26 15:16 UTC, tvz-041 commented on Lab 1 "External (file) sorts"/Lab 1 "External (file) sorts"/main.cpp
> +    const int P = Естественная_Сортировка;
```suggestion
    const SortTypes sortType = SortTypes::NaturalMerge;
```

2024-03-26 15:16 UTC, tvz-041 commented on Lab 1 "External (file) sorts"/Lab 1 "External (file) sorts"/main.cpp
> +        case 0:
Какой толк от перечисления, если вы дальше его не используете?
```suggestion
    switch (sortType ) {
        case SortType::DirectMerge:
```

2024-03-26 15:16 UTC, tvz-041 commented on Lab 1 "External (file) sorts"/Lab 1 "External (file) sorts"/main.cpp
> +enum SortTypes {Прямая_Сортировка = 0, Естественная_Сортировка = 1};
Ну кириллицу-то зачем сюда?...
```suggestion
enum SortType
{
    DirectMerge,
    NaturalMerge
};
```
Как и в случае с классами, множественное число использовать не следует. Оно +- нормально выглядит при объявлении класса, но будет путать при создании переменных:
```c++
    SortTypes sortType = SortTypes::DirectMerge;
```

P.S. Т.к. enum используется в функции, то и объявлен он должен быть там же.

2024-03-27 11:12 UTC, antoniovay commented
Исправил ошибки с enum

2024-04-04 06:42 UTC, tvz-041 commented
https://github.com/github/gitignore/blob/main/Swift.gitignore

2024-04-04 07:04 UTC, tvz-041 approved these changes

2024-04-04 07:05 UTC, merged